name: flutter_form_builder
description: Package to build Material Form with components such as TextField, DropDown, TypeAhead, Radios, Checkboxes, Stepper, Slider DateTimePickers and ability to create custom formfields which also allows composability and/or reuse validation functions.
version: 3.0.1
author: Danvick Miller <danvickmiller@gmail.com>
homepage: https://github.com/danvick/flutter_form_builder

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_typeahead: ^1.4.0
  intl: ^0.15.7
  sy_flutter_widgets: ^0.1.4
  flutter_chips_input: ^1.2.0
  datetime_picker_formfield: ^0.1.8
  # signature: ^2.0.0 - Doesn't implement onChanged, submitted PR. Meanwhile using local clone with onChanged
  validators: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 1.6.3

flutter:
